name: Android CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
      - uses: actions/checkout@v3

      - name: Access properties
        env:
          GSI_WEB_CLIENT_ID: $
        run: echo GSI_WEB_CLIENT_ID=\"GSI_WEB_CLIENT_ID\" > ./local.properties

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup gradle
        run: gradle/gradle-build-action@v2

      - name: Run unit tests
        run: ./gradlew test

      - name: Build project
        run: ./gradlew assemble
