name: Android Build

on:
  pull_request:
    branches:
      - '**'

jobs:
  build_app:
    name: Building app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Access properties
        env:
          GSI_WEB_CLIENT_ID: $
        run: echo GSI_WEB_CLIENT_ID=\"GSI_WEB_CLIENT_ID\" > ./local.properties

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Run Tests
        run: gradlew test --stacktrace

      - name: Build project
        run: gradlew build --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/**.apk
